services:
  - type: web
    name: increnation-payment-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: PAYTM_ENV
        value: staging
      - key: PAYTM_WEBSITE
        value: WEBSTAGING
      - key: PAYTM_CHANNEL_ID
        value: WEB
      - key: PAYTM_INDUSTRY_TYPE
        value: Retail
      - key: PAYTM_MID
        sync: false
      - key: PAYTM_MERCHANT_KEY
        sync: false
      - key: PAYTM_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
